### ISSUE TITLE
How do you change routes...

### ISSUE THREAD

**Issue by bingomanatee** [kriasoft/react-routing#16]
without reloading the page? there are tricks like transitionTo and history in react-router; do these work with react-routing as well?

Dave

**Comment by subodh-malgonde** [comment]
If you are using the [react-starter-kit](https://github.com/kriasoft/react-starter-kit), then there is a [Location](https://github.com/kriasoft/react-starter-kit/blob/master/src/core/Location.js) module. Use       

    Location.pushState(null, '/to/path')

**Comment by subodh-malgonde** [comment]
@koistya is this the right way?

**Comment by koistya** [comment]
Check the new [`history` API documentation](https://github.com/rackt/history/tree/master/docs). `Location` is an instance of `history` module. You can use it to transition between screens/pages on the client.

```js
Location.push('/to/path');
Location.push({ pathname: '/to/path', state: { foo: 123 } });
```

**Comment by alexgvozden** [comment]
what happened to Location and what is the replacement?
