### ISSUE TITLE
Problem with history on Chrome for iOS?

### ISSUE THREAD

**Issue by subodh-malgonde** [kriasoft/react-routing#21]
I have used react-routing in my react app (via [react-starter-kit](https://github.com/kriasoft/react-starter-kit/)). It works fine on all browsers except for Chrome on iOS. The root url keeps on reloading. I was looking for possible causes and stumbled across this thread on [react-router](https://github.com/reactjs/react-router/issues/2565). There was some issue with history api. I am guessing a similar issue for react-routing. I din't find a way to debug chrome on ios. Can anyone help?

**Comment by koistya** [comment]
This library does handle only routing itself and not the navigation. It can be combined with any HTML5 History API based library like `history` that used in `react-router` and RSK. It seems like the issue you're describing is related to the `history` module. You may want to try [history.js](https://github.com/browserstate/history.js) as an alternative solution for client-side navigation.
