### ISSUE TITLE
state doesn't have param

### ISSUE THREAD

**Issue by constantx** [kriasoft/react-routing#6]
<img width="548" alt="recipes" src="https://cloud.githubusercontent.com/assets/113969/9030634/071e1e88-395a-11e5-93e8-039ea9749805.png">

I'm expecting `state.params.recipeId`, but `params` doesn't exist on the `state` object.

**Comment by lehneres** [comment]
seems to be solved in 0.0.4

**Comment by koistya** [comment]
Yep, this one is fixed in 0.0.4

**Comment by maysale01** [comment]
Issue still persists,

```

**Comment by maysale01** [comment]
The issue is that `/lib/` doesn't contain 0.0.4 when you do `npm install react-routing`. If I clone this repo and run `npm run build` and copy the lib folder to my project it works.

**Comment by maysale01** [comment]
Fixed in 0.0.5 This can be closed.
